In [2]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv('spam.csv')
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [7]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [9]:
df['spam']=df['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [12]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [14]:
df.shape

(5572, 3)

In [25]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df['Message'],df['spam'],test_size=0.2)

In [26]:
X_train.shape

(4457,)

In [27]:
type(X_train)

pandas.core.series.Series

In [28]:
X_train

1431    Don't look back at the building because you ha...
1856    K.:)you are the only girl waiting in reception...
4005    Well there's a pattern emerging of my friends ...
2699                             FROM 88066 LOST £12 HELP
1422                          Do you work all this week ?
                              ...                        
4904                     I;m reaching in another 2 stops.
968     What do u want when i come back?.a beautiful n...
4433    Dont think you need yellow card for uk travel....
1100    Been up to ne thing interesting. Did you have ...
4223    Yo you around? A friend of mine's lookin to pi...
Name: Message, Length: 4457, dtype: object

In [29]:
type(y_train)

pandas.core.series.Series

In [30]:
y_train

1431    0
1856    0
4005    0
2699    1
1422    0
       ..
4904    0
968     0
4433    0
1100    0
4223    0
Name: spam, Length: 4457, dtype: int64

In [33]:
type(X_train.values)

numpy.ndarray

In [35]:
from sklearn.feature_extraction.text import CountVectorizer
v=CountVectorizer()
X_train_cv=v.fit_transform(X_train.values)
X_train_cv

<4457x7793 sparse matrix of type '<class 'numpy.int64'>'
	with 59399 stored elements in Compressed Sparse Row format>

In [36]:
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [37]:
X_train_cv.shape

(4457, 7793)

In [40]:
v.get_feature_names_out()

array(['00', '000', '000pes', ..., 'zoom', 'zouk', 'èn'], dtype=object)

In [41]:
v.get_feature_names_out().shape

(7793,)

In [42]:
v.vocabulary_

{'don': 2419,
 'look': 4241,
 'back': 1193,
 'at': 1115,
 'the': 6849,
 'building': 1553,
 'because': 1274,
 'you': 7759,
 'have': 3395,
 'no': 4843,
 'coat': 1881,
 'and': 958,
 'want': 7427,
 'to': 6968,
 'get': 3153,
 'more': 4630,
 'sick': 6197,
 'just': 3917,
 'hurry': 3603,
 'home': 3516,
 'wear': 7470,
 'gym': 3323,
 'are': 1048,
 'only': 4994,
 'girl': 3173,
 'waiting': 7405,
 'in': 3692,
 'reception': 5677,
 'ah': 866,
 'well': 7502,
 'there': 6868,
 'pattern': 5171,
 'emerging': 2593,
 'of': 4941,
 'my': 4713,
 'friends': 3032,
 'telling': 6793,
 'me': 4457,
 'drive': 2469,
 'up': 7227,
 'come': 1915,
 'smoke': 6305,
 'with': 7596,
 'them': 6858,
 'then': 6862,
 'that': 6845,
 'weed': 7486,
 'fiend': 2852,
 'make': 4374,
 'too': 7010,
 'much': 4680,
 'impede': 3678,
 'their': 6855,
 'doing': 2411,
 'other': 5051,
 'things': 6881,
 'so': 6327,
 'see': 6031,
 'how': 3566,
 'hesitant': 3457,
 'from': 3049,
 '88066': 695,
 'lost': 4258,
 '12': 275,
 'help': 3439,
 'do': 2387,
 'w

In [45]:
X_train_np=X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [47]:
np.where(X_train_np[0]!=0) #the values in output is the vector number of email

(array([ 958, 1115, 1193, 1274, 1553, 1881, 2419, 3153, 3323, 3395, 3516,
        3603, 3917, 4241, 4630, 4843, 6197, 6849, 6968, 7427, 7470, 7759],
       dtype=int64),)

In [53]:
X_train[1431]

"Don't look back at the building because you have no coat and i don't want you to get more sick. Just hurry home and wear a coat to the gym!!!"

In [56]:
X_train_np[0][958] #bcz "and" comes twice in email

2

In [61]:
v.get_feature_names_out()[958]

'and'

In [62]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(X_train_cv,y_train)

MultinomialNB()

In [63]:
X_test_cv=v.transform(X_test)

The history saving thread hit an unexpected error (OperationalError('database or disk is full')).History will not be written to the database.


In [67]:
from sklearn.metrics import classification_report
y_pred=model.predict(X_test_cv)
cls=classification_report(y_test,y_pred)
print(cls)

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       950
           1       0.98      0.90      0.94       165

    accuracy                           0.98      1115
   macro avg       0.98      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [70]:
emails=[
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
emails_count=v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

Alternative and simple way to classify the spam by using pipeline

In [71]:
from sklearn.pipeline import Pipeline
clf=Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [72]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [76]:
y_pred = clf.predict(X_test)
print(classification_report (y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       950
           1       0.98      0.90      0.94       165

    accuracy                           0.98      1115
   macro avg       0.98      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [77]:
emails=[
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
emails_count=v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)